#!/bin/sh
less <<'EOF'
================================================================
  RESCUE EFI MINI -- Quick Reference
================================================================

WHAT THIS IS
  Minimal rescue: disk tools, filesystem repair, EFI boot management.
  Kernel + rootfs are embedded -- no disk needed to boot.
  Built with: make mini   from github.com/prithivirajasingh5/uki

----------------------------------------------------------------
  DISK + HARDWARE INSPECTION
----------------------------------------------------------------
  lsblk -f              list disks and partitions with filesystems
  blkid                 show UUIDs and filesystem types
  fdisk -l              list partition tables
  nvme list             list NVMe drives
  nvme smart-log /dev/nvme0   NVMe health info
  lspci                 list PCI devices
  lsusb                 list USB devices
  lshw                  full hardware inventory

----------------------------------------------------------------
  PARTITIONING
----------------------------------------------------------------
  parted /dev/nvme0n1 print
  parted /dev/nvme0n1 mklabel gpt
  parted /dev/nvme0n1 mkpart primary ext4 1MiB 50GiB
  gdisk /dev/nvme0n1        interactive GPT editor

----------------------------------------------------------------
  FILESYSTEMS
----------------------------------------------------------------
  mkfs.ext4 /dev/nvme0n1p2
  mkfs.fat -F32 /dev/nvme0n1p1     (EFI partition)
  mkfs.btrfs /dev/nvme0n1p2
  fsck.ext4 /dev/nvme0n1p2
  mount /dev/nvme0n1p2 /mnt
  umount /mnt

----------------------------------------------------------------
  EFI BOOT MANAGEMENT
----------------------------------------------------------------
  efibootmgr -v                        list all boot entries
  efibootmgr --delete-bootnum --bootnum 0003
  efibootmgr --create --disk /dev/nvme0n1 --part 1 \
    --label "Linux" --loader '\EFI\ubuntu\grubx64.efi'

  Reinstall GRUB:
    mount /dev/nvme0n1p2 /mnt
    mount /dev/nvme0n1p1 /mnt/boot/efi
    mount --bind /dev  /mnt/dev
    mount --bind /proc /mnt/proc
    mount --bind /sys  /mnt/sys
    chroot /mnt
    grub-install --target=x86_64-efi --efi-directory=/boot/efi
    update-grub
    exit

----------------------------------------------------------------
  FILES + EDITING
----------------------------------------------------------------
  nano /mnt/boot/grub/grub.cfg
  nano /mnt/etc/fstab
  find /mnt -name "grub.cfg"
  less /mnt/var/log/syslog

----------------------------------------------------------------
  SYSTEM
----------------------------------------------------------------
  Reboot:   reboot
  Poweroff: poweroff

================================================================

EOF
